### ISSUE TITLE
Request to mining

### ISSUE THREAD

**Issue by bilalamjad837** [Sanix-Darker/Hono#3]
hey can you help me please  i need your very important time please  

I finish all code like you write.
And also follow your "How to run" instructions.
But when i click any buttons on the webpages, there is a Not Found error.

![14](https://user-images.githubusercontent.com/56451787/68118862-f4bbe100-feb5-11e9-90ec-2307fc1a3b0a.PNG)
![13](https://user-images.githubusercontent.com/56451787/68118872-fc7b8580-feb5-11e9-8428-3f413f35b02c.PNG)

**Comment by Sanix-Darker** [comment]
i don't understand this issue, nothing to do with the current project !
